### ISSUE TITLE
[nuxt] [request error] fetch failed - while serving app locally

### ISSUE THREAD

**Issue by PatrikBird** [Atinux/content-wind#15]
Getting this error spammed after I try to visit the locally served app. Using M1 mac, yarn 1.22.17 - any idea? I basically just cloned and installed dependencies.
```
[nuxt] [request error] fetch failed ()
  at createError (./node_modules/h3/dist/index.mjs:191:15)
  at nodeHandler (./node_modules/h3/dist/index.mjs:381:21)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:336:16)
  at async nodeHandler (./node_modules/h3/dist/index.mjs:389:9)
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)
  at async $fetchRaw2 (./node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
  at async Object.errorhandler [as onError] (./.nuxt/dev/index.mjs:336:16)
[h3] [unhandled] H3Error: fetch failed ()
    at createError (file:///Users/bird/GitHub/wtfffff/node_modules/h3/dist/index.mjs:191:15)
    at nodeHandler (file:///Users/bird/GitHub/wtfffff/node_modules/h3/dist/index.mjs:381:21)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ufetch (file:///Users/bird/GitHub/wtfffff/node_modules/unenv/runtime/fetch/index.mjs:9:17)
    at async $fetchRaw2 (file:///Users/bird/GitHub/wtfffff/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
    at async Object.errorhandler [as onError] (file:///Users/bird/GitHub/wtfffff/.nuxt/dev/index.mjs:336:16)
    at async nodeHandler (file:///Users/bird/GitHub/wtfffff/node_modules/h3/dist/index.mjs:389:9)
    at async ufetch (file:///Users/bird/GitHub/wtfffff/node_modules/unenv/runtime/fetch/index.mjs:9:17)
    at async $fetchRaw2 (file:///Users/bird/GitHub/wtfffff/node_modules/ohmyfetch/dist/chunks/fetch.mjs:131:20)
    at async Object.errorhandler [as onError] (file:///Users/bird/GitHub/wtfffff/.nuxt/dev/index.mjs:336:16) {
  statusCode: 500,
  fatal: false,
  unhandled: true,
  statusMessage: 'Internal Server Error'
}
```

**Comment by Atinux** [comment]
Can you try again with latest changes?

**Comment by Atinux** [comment]
An re-open if this is still the case
